# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lade < Formula
  desc "Developer tool to manage your apps"
  homepage "https://github.com/lade-io/lade"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lade-io/lade/releases/download/v0.1.5/lade-darwin-arm64.tar.gz"
      sha256 "820bbb8691ff6e5d232402bbbe7cce248b975af48562fd2c16d46771de8d9dbc"

      def install
        bin.install "lade"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lade-io/lade/releases/download/v0.1.5/lade-darwin-amd64.tar.gz"
      sha256 "b6106149a980c7de05b0488923bf6051622e5db9309eef2abe55f47e38dbd5ad"

      def install
        bin.install "lade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lade-io/lade/releases/download/v0.1.5/lade-linux-arm64.tar.gz"
      sha256 "d9eace9b45d1a89e639e1efe728c5eb2772d7e54bb555f624619f71f4f56dd44"

      def install
        bin.install "lade"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lade-io/lade/releases/download/v0.1.5/lade-linux-amd64.tar.gz"
      sha256 "d18060639aa82dc3928cbb562c245e0b2088d50c6c472428c0d3f40dcffc0a83"

      def install
        bin.install "lade"
      end
    end
  end
end
