# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lade < Formula
  desc "Developer tool to manage your apps"
  homepage "https://github.com/lade-io/lade"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lade-io/lade/releases/download/v0.1.2/lade-darwin-arm64.tar.gz"
      sha256 "0528b0c4d6c5259d61242a87882f20a8b1d73fbd6c420710af6063d5cb13d1fb"

      def install
        bin.install "lade"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lade-io/lade/releases/download/v0.1.2/lade-darwin-amd64.tar.gz"
      sha256 "39e5dda7c8ea93a66748aca33423dcc2e2ecc6b4ab343f3c20f426f347999a0e"

      def install
        bin.install "lade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lade-io/lade/releases/download/v0.1.2/lade-linux-arm64.tar.gz"
      sha256 "1ee35184b80140588fa81631c864a06c7bd98fc1858af2eb68b30bbc819bbe99"

      def install
        bin.install "lade"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lade-io/lade/releases/download/v0.1.2/lade-linux-amd64.tar.gz"
      sha256 "187c713fb3b63e5ca41e935e65e580e935d0d205d92264dea30e59150ab07cd0"

      def install
        bin.install "lade"
      end
    end
  end
end
